1/niji/niji/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from rest_framework import routers
from niji import api
from niji import views

api_router = routers.DefaultRouter()
api_router.register(r'topics', api.TopicApiView)
api_router.register(r'post', api.PostApiView)

app_name = 'niji'

urlpatterns = [
    url(r'^page/(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    url(r'^$', views.home, name='home'),
    url(r'index/', views.Index.as_view(), name='index'),
    url(r'^n/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', views.NodeView.as_view(), name='node'),
    url(r'^n/(?P<pk>\d+)/$', views.NodeView.as_view(), name='node'),
    url(r'^t/(?P<pk>\d+)/edit/$', views.edit_topic, name='edit_topic'),
    url(r'^t/(?P<pk>\d+)/append/$', views.create_appendix, name='create_appendix'),
    url(r'^t/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^t/(?P<pk>\d+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^u/(?P<pk>\d+)/$', views.user_info, name='user_info'),
    url(r'^u/(?P<pk>\d+)/topics/page/(?P<page>[0-9]+)/$', views.UserTopics.as_view(), name='user_topics'),
    url(r'^u/(?P<pk>\d+)/topics/$', views.UserTopics.as_view(), name='user_topics'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^reg/$', views.reg_view, name='reg'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^search/$', views.search_redirect, name='search_redirect'),
    url(r'^search/(?P<keyword>.*?)/page/(?P<page>[0-9]+)/$', views.SearchView.as_view(), name='search'),
    url(r'^search/(?P<keyword>.*?)/$', views.SearchView.as_view(), name='search'),
    url(r'^t/create/$', views.create_topic, name='create_topic'),
    url(r'^notifications/$', views.NotificationView.as_view(), name='notifications'),
    url(r'^avatar/$', views.upload_avatar, name="upload_avatar"),
    url(r'^uploads/(?P<path>.*?)/(?P<subpath>.*?)/(?P<filename>.*?)/$', views.get_upload_file, name="get_upload_file"),
    url(r'^.*?/uploads/(?P<path>.*?)/(?P<subpath>.*?)/(?P<filename>.*?)/$', views.get_upload_file, name="get_upload_file"),
    url(r'^api/', include(api_router.urls)),
    url(r'^test$', views.test),
    url(r'^test/tang$', views.tang),
    url(r'^test/song$', views.song),
    url(r'^test/success$', views.success),
]

1/niji/urls.py
from django.urls import path
from django.conf.urls import include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('niji.urls')),
    path('tp/', include('tp.urls')),
    path('xj/', include('xj.urls')),
    path('NER/', include('NER.urls')),
    path('fhl/', include('fhl.urls'))
]

1/niji/niji/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import F
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db.models.deletion import CASCADE
from django.urls import reverse
# from django.utils.encoding import python_2_unicode_compatible
from six import python_2_unicode_compatible
from django.utils.translation import gettext as _
from functools import partial
from niji.tasks import notify
from PIL import Image
from io import BytesIO
import xxhash
import mistune
import re
import importlib
import six
if six.PY2:
    import sys
    importlib.reload(sys) # 设置python的默认编码,Python3字符串默认编码unicode
    #
    # import sys
    # reload(sys)
    # sys.setdefaultencoding('utf-8')


MENTION_REGEX = re.compile(r'@(\S+)', re.M)
USER_MODEL = settings.AUTH_USER_MODEL


def _replace_username(link, matchobj):
    return "@<a href=\"{link}\">{username}</a>{whitespace}".format(
        username=matchobj.group("username")[1:],
        whitespace=matchobj.group("whitespace"),
        link=link
    )


def render_content(content_raw, sender):
    """
    :param content_raw: Raw content
    :param sender: user as username
    :return: (rendered_content, mentioned_user_list)
    """
    content_rendered = mistune.markdown(content_raw)
    mentioned = list(set(re.findall(MENTION_REGEX, content_raw)))
    mentioned = [x for x in mentioned if x != sender]
    mentioned_users = get_user_model().objects.filter(username__in=mentioned)
    for user in mentioned_users:
        content_rendered = re.sub(
            r'(?P<username>@%s)(?P<whitespace>\s|<\/p>)' % user.username,
            partial(_replace_username, reverse('niji:user_info', kwargs={"pk": user.pk})),
            content_rendered,
            re.M
        )
    return content_rendered, mentioned_users


class TopicQueryset(models.QuerySet):

    def visible(self):
        return self.filter(hidden=False)


@python_2_unicode_compatible
class Topic(models.Model):
    user = models.ForeignKey(USER_MODEL, related_name='topics', verbose_name=_("user"), on_delete=models.CASCADE)
    title = models.CharField(max_length=120, verbose_name=_("title"))
    content_raw = models.TextField(verbose_name=_("raw content"))
    content_rendered = models.TextField(default='', blank=True, verbose_name=_("rendered content"))
    view_count = models.IntegerField(default=0, verbose_name=_("view count"))
    reply_count = models.IntegerField(default=0, verbose_name=_("reply count"))
    node = models.ForeignKey('Node', related_name='topics', verbose_name=_("node"), on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=_("published time"))
    last_replied = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=_("last replied time"))
    order = models.IntegerField(default=10, verbose_name=_("order"))
    hidden = models.BooleanField(default=False, verbose_name=_("hidden"))
    closed = models.BooleanField(default=False, verbose_name=_("closed"))
    objects = TopicQueryset.as_manager()

    raw_content_hash = None

    def __init__(self, *args, **kwargs):
        super(Topic, self).__init__(*args, **kwargs)
        self.raw_content_hash = xxhash.xxh64(self.content_raw).hexdigest()

    def get_reply_count(self):
        return self.replies.visible().count()

    def get_last_replied(self):
        last_visible_reply = self.replies.visible().order_by('-pub_date').first()
        if last_visible_reply:
            return last_visible_reply.pub_date
        return self.pub_date

    def increase_view_count(self):
        Topic.objects.filter(pk=self.id).update(view_count=F('view_count') + 1)

    def save(self, *args, **kwargs):
        new_hash = xxhash.xxh64(self.content_raw).hexdigest()
        mentioned_users = []
        if new_hash != self.raw_content_hash or (not self.pk):
            # To (re-)render the content if content changed or topic is newly created
            self.content_rendered, mentioned_users = render_content(self.content_raw, sender=self.user.username)
        super(Topic, self).save(*args, **kwargs)
        self.raw_content_hash = new_hash
        for to in mentioned_users:
                notify.delay(to=to.username, sender=self.user.username, topic=self.pk)

    class Meta:
        ordering = ['order', '-pub_date']

    def __str__(self):
        return self.title


class PostQueryset(models.QuerySet):

    use_for_related_fields = True

    def visible(self):
        return self.filter(hidden=False)


@python_2_unicode_compatible
class Post(models.Model):
    topic = models.ForeignKey('Topic', related_name='replies', verbose_name=_("topic"), on_delete=models.CASCADE)
    user = models.ForeignKey(USER_MODEL, related_name='posts', verbose_name=_("user"), on_delete=models.CASCADE)
    content_raw = models.TextField(verbose_name=_("raw content"))
    content_rendered = models.TextField(default='', verbose_name=_("rendered content"))
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name=_("published time"))
    hidden = models.BooleanField(default=False, verbose_name=_("hidden"))
    objects = PostQueryset.as_manager()

    raw_content_hash = None

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.raw_content_hash = xxhash.xxh64(self.content_raw).hexdigest()

    def __str__(self):
        return 'Reply to %s' % self.topic.title

    def save(self, *args, **kwargs):
        new_hash = xxhash.xxh64(self.content_raw).hexdigest()
        mentioned_users = []
        if new_hash != self.raw_content_hash or (not self.pk):
            self.content_rendered, mentioned_users = render_content(self.content_raw, sender=self.user.username)
        super(Post, self).save(*args, **kwargs)
        t = self.topic
        t.reply_count = t.get_reply_count()
        t.last_replied = t.get_last_replied()
        t.save(update_fields=['last_replied', 'reply_count'])
        for to in mentioned_users:
            notify.delay(to=to.username, sender=self.user.username, post=self.pk)

    def delete(self, *args, **kwargs):
        super(Post, self).delete(*args, **kwargs)
        t = self.topic
        t.reply_count = t.get_reply_count()
        t.last_replied = t.get_last_replied()
        t.save(update_fields=['last_replied', 'reply_count'])


@python_2_unicode_compatible
class Notification(models.Model):
    sender = models.ForeignKey(USER_MODEL, related_name='sent_notifications', verbose_name=_("sender"), on_delete=models.CASCADE)
    to = models.ForeignKey(USER_MODEL, related_name='received_notifications', verbose_name=_("recipient"), on_delete=models.CASCADE)
    topic = models.ForeignKey('Topic', null=True, verbose_name=_("topic"), on_delete=models.CASCADE)
    post = models.ForeignKey('Post', null=True, verbose_name=_("reply"), on_delete=models.CASCADE)
    read = models.BooleanField(default=False, verbose_name=_("read"))
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name=_("published time"))

    def __str__(self):
        return 'Notification from %s to %s' % (self.sender.username, self.to.username)


@python_2_unicode_compatible
class Appendix(models.Model):
    topic = models.ForeignKey('Topic', verbose_name=_("topic"), on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name=_("published time"))
    content_raw = models.TextField(verbose_name=_("raw content"))
    content_rendered = models.TextField(default='', blank=True, verbose_name=_("rendered content"))

    raw_content_hash = None

    def __init__(self, *args, **kwargs):
        super(Appendix, self).__init__(*args, **kwargs)
        self.raw_content_hash = xxhash.xxh64(self.content_raw).hexdigest()

    def save(self, *args, **kwargs):
        new_hash = xxhash.xxh64(self.content_raw).hexdigest()
        if new_hash != self.raw_content_hash or (not self.pk):
            self.content_rendered = mistune.markdown(self.content_raw)
        super(Appendix, self).save(*args, **kwargs)
        self.raw_content_hash = new_hash

    def __str__(self):
        return 'Appendix to %s' % self.topic.title


@python_2_unicode_compatible
class Node(models.Model):
    title = models.CharField(max_length=30, verbose_name=_("title"))
    description = models.TextField(default='', blank=True, verbose_name=_("description"))

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class NodeGroup(models.Model):
    title = models.CharField(max_length=30)
    node = models.ManyToManyField('Node')

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class ForumAvatar(models.Model):
    user = models.OneToOneField(USER_MODEL, related_name='forum_avatar', on_delete=models.CASCADE)
    use_gravatar = models.BooleanField(default=False)
    image = models.ImageField(max_length=255,
                              upload_to='uploads/forum/avatars/',
                              blank=True,
                              default="",
                              null=True)

    def save(self, *args, **kwargs):
        existing_avatar = ForumAvatar.objects.filter(user=self.user).first()
        if existing_avatar:
            self.id = existing_avatar.id
        if not self.image:
            self.use_gravatar = True
        else:
            i = Image.open(self.image)
            i.thumbnail((120, 120), Image.ANTIALIAS)
            i_io = BytesIO()
            i.save(i_io, format='PNG')
            self.image = InMemoryUploadedFile(
                i_io, None, '%s.png' % self.user_id, 'image/png', None, None
            )
        print(self.image)
        super(ForumAvatar, self).save(*args, **kwargs)

    def __str__(self):
        return "Avatar for user: %s" % self.user.username


class favourite(models.Model):

1/niji/niji/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django.conf import settings
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper
from .models import Topic, Appendix, ForumAvatar, Post
from django.utils.translation import ugettext as _

if 'pagedown' in settings.INSTALLED_APPS:
    use_pagedown = True
    from django import forms
    from pagedown.widgets import PagedownWidget
else:
    use_pagedown = False


class TopicForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TopicForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ['node', 'title', 'content_raw']
        labels = {
            'content_raw': _('Content'),
            'node': _('Node'),
            'title': _('Title'),
        }

    def save(self, commit=True):
        inst = super(TopicForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class TopicEditForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(TopicEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ('content_raw', )
        labels = {
            'content_raw': _('Content'),
        }


class AppendixForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.topic = kwargs.pop('topic', None)
        super(AppendixForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Appendix
        fields = ('content_raw', )
        labels = {
            'content_raw': _('Content'),
        }

    def save(self, commit=True):
        inst = super(AppendixForm, self).save(commit=False)
        inst.topic = self.topic
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ForumAvatarForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ForumAvatarForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = ForumAvatar
        fields = ('image', 'use_gravatar')
        labels = {
            'image': _('Avatar Image'),
            'use_gravatar': _("Always Use Gravatar")
        }

    def save(self, commit=True):
        inst = super(ForumAvatarForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ReplyForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label='', widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic_id = kwargs.pop('topic_id', None)
        super(ReplyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Post
        fields = ('content_raw',)
        labels = {
            'content_raw': '',
        }

    def save(self, commit=True):
        inst = super(ReplyForm, self).save(commit=False)
        inst.user = self.user
        inst.topic_id = self.topic_id
        if commit:
            inst.save()
            self.save_m2m()
        return inst

1/niji/niji/templates/niji/create_appendix.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block left %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form method="post" action="{% url "niji:create_appendix" pk=pk %}">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

1/niji/niji/templates/niji/create_topic.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block left %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form method="post" action="{% url "niji:create_topic" %}">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

1/niji/niji/templates/niji/topic.html
{% extends 'niji/base.html' %}
{% load i18n %}
{% load niji_tags %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block left %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-body">
            <ol class="breadcrumb">
                <li><a href="{% url 'niji:index' %}">Home</a></li>
                <li><a href="{% url 'niji:node' pk=topic.node.pk %}">{{ topic.node.title }}</a></li>
                <li class="active">{{ topic.title }}</li>
            </ol>
            <h1 class="topic-title">{{ topic.title }}</h1>
            <div class="topic-meta row">
                <div class="col-xs-2 col-sm-1">
                    <img class="user-avatar" src="{% avatar_url topic.user %}" alt=""/>
                </div>
                <div class="col-xs-9 col-sm-10">
                    <p class="text-muted">
                        <a href="{% url 'niji:user_info' topic.user.pk %}">{{ topic.user.username }}</a>
                        <br/>
                        <span>Posted {{ topic.pub_date | naturaltime }} in <a class="text-primary" href="{% url 'niji:node' pk=topic.node.pk %}">{{ topic.node.title }}</a>, </span>
                        <span>{% blocktrans with view_count=topic.view_count %}viewed {{ view_count }} times{% endblocktrans %}</span>
                    </p>
                </div>
            </div>
            <div class="topic-content">
                <p>{{ topic.content_rendered | safe}}</p>
            </div>
        </div>
        {% if topic.appendix_set %}
            <ul class="list-group">
                {% for appendix in topic.appendix_set.all %}
                    <div class="list-group-item list-appendix-item">
                        <p class="appendix-meta">
                            {% blocktrans with number=forloop.counter %}appendix {{number}}{% endblocktrans %} {{appendix.pub_date|naturaltime}}
                        </p>
                        {{appendix.content_rendered | safe}}
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
        {% if request.user == topic.user %}
            <div class="panel-footer">
                {% if topic.reply_count == 0 %}
                    <a href="{% url 'niji:edit_topic' pk=topic.pk %}"><span class="label label-success">{% trans 'Edit' %}</span></a>
                {% endif %}
                <a href="{% url 'niji:create_appendix' pk=topic.pk %}"><span class="label label-warning">{% trans 'Append' %}</span></a>
            </div>
        {% endif %}
        {% if request.user.is_superuser %}
            <div class="panel-footer">
                <span>{% trans 'Moderations' %}: </span>
                <a href="#" class="moderate-action move-topic-up" data-toggle="modal" data-target="#moderation-modal" data-pk="{{ topic.pk }}" data-action="move-topic-up" data-api-url="{% url 'niji:topic-detail' topic.pk %}">
                    <span class="label label-success">Up</span>
                </a>
                {% if topic.closed %}
                    <a href="#" class="moderate-action open-topic" data-toggle="modal" data-target="#moderation-modal" data-pk="{{ topic.pk }}" data-action="open-topic" data-api-url="{% url 'niji:topic-detail' topic.pk %}">
                        <span class="label label-info">Open</span>
                    </a>
                {% else %}
                    <a href="#" class="moderate-action close-topic" data-toggle="modal" data-target="#moderation-modal" data-pk="{{ topic.pk }}" data-action="close-topic" data-api-url="{% url 'niji:topic-detail' topic.pk %}">
                        <span class="label label-warning">Close</span>
                    </a>
                {% endif %}
                <a href="#" class="moderate-action hide-topic" data-toggle="modal" data-target="#moderation-modal" data-pk="{{ topic.pk }}" data-action="hide-topic" data-api-url="{% url 'niji:topic-detail' topic.pk %}">
                    <span class="label label-danger">Hide</span>
                </a>
            </div>
        {% endif %}
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            {% if topic.reply_count %}
                {% blocktrans count reply_count=topic.reply_count %}{{ reply_count }} Reply{% plural %}{{ reply_count }} Replies{% endblocktrans %}
            {% else %}
                {% trans "No Replies" %}
            {% endif %}
        </div>
        <!-- List group -->
        <ul class="list-group reply-list">
            {% for post in posts %}
                <li class="list-group-item reply-item">
                    <div class="topic-meta row">
                        <div class="col-xs-2 col-sm-1">
                            <img class="user-avatar" src="{% avatar_url post.user %}" alt=""/>
                        </div>
                        <div class="col-xs-9 col-sm-10">
                            <p class="text-muted">
                                <a href="{% url 'niji:user_info' post.user_id %}">{{ post.user }}</a> <br/>
                                <span>{{ post.pub_date | naturaltime }}</span>
                            </p>
                        </div>
                    </div>
                    <div class="reply-content">
                        <p>
                            {{ post.content_rendered | safe}}
                        </p>
                    </div>
                    <p class="reply-link">
                        <a href="#" data-username="{{ post.user.username }}" class="reply-to">{% trans "Reply" %}</a>
                    </p>
                    {% if request.user.is_superuser %}
                        <hr>
                        <p class="moderation-links">
                            <a href="#" class="moderate-action hide-reply" data-toggle="modal" data-target="#moderation-modal" data-pk="{{ topic.pk }}" data-action="hide-reply" data-api-url="{% url 'niji:post-detail' post.pk %}">
                                <span class="label label-danger">Hide</span>
                            </a>
                        </p>
                    {% endif %}
                </li>
            {% endfor %}
            {% if not posts %}
                <li class="list-group-item reply-item"><p>{% trans "Be the first to reply!" %}</p></li>
            {% endif %}
        </ul>
        <div class="panel-footer">
            {% get_pagination %}
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">{% trans "Leave a Reply"%}</div>
        <div class="panel-body">
            {% if topic.closed %}
                <div class="alert alert-warning" role="alert">
                    <p>{% trans "This topic is closed" %}</p>
                </div>
            {% else %}
                {% if request.user.is_authenticated %}
                    <form action="{% url 'niji:topic' pk=topic.pk %}" method="POST">
                        {% crispy form %}
                    </form>
                {% else %}
                    <div class="alert alert-warning" role="alert">
                        {% url niji_login_url_name as login_url %}
                        {% url niji_reg_url_name as reg_url %}
                        {% blocktrans %}
                            Please <a href="{{ login_url }}">Login</a> or <a href="{{ reg_url }}">Create a New User</a> to reply
                        {% endblocktrans %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block widget_after %}
    {% include 'niji/widgets/node_info.html' %}
{% endblock %}

{% block footer_ext %}
    <script>
        $(document).ready(function(){
            $('.reply-to').click(function(e){
                e.preventDefault();
                var box = $("#reply-content-input, #id_content_raw");
                box.val(box.val() + "@"+$(this).data('username')+"\n");
            });
        });
    </script>
    {% if request.user.is_superuser %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.12.0/babel.min.js"></script>
        <div id="moderation-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        <p>One fine body&hellip;</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-warning modal-confirm">Confirm</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <script type="text/babel">
            let patchTopic = function(url, data){
                $.ajax({
                    dataType: 'json',
                    method: 'PATCH',
                    url: url,
                    data: data
                }).done(()=>{
                    $('#moderation-modal').find('.modal-body').html(`<p class="text-success">{% trans 'Operation successful' %}</p>`);
                }).fail((xhr, status, error)=>{
                    $('#moderation-modal').find('.modal-body').html(`<p class="text-danger">${status}</p>`);
                    console.log(xhr.responseText);
                    console.log(error);
                }).always(()=>{
                    $('.modal-confirm').hide();
                });
            };
            $('#moderation-modal').on('show.bs.modal', function (event) {
                $('.modal-confirm').show();
                let button = $(event.relatedTarget);
                let recipient = button.data('whatever');
                let modal = $(this);
                let modalTitle;
                let modalBody;
                let modalCb;
                switch (button.data('action')) {
                    case 'move-topic-up':
                        modalTitle = '{% trans 'Stick to Top' %}';
                        modalBody = `<form>
                              <div class="form-group">
                                <label for="recipient-name" class="control-label">{% trans 'Level (1 - Highest)' %}:</label>
                                <select class="form-control" name="move-topic-up-level">
                                  <option>1</option>
                                  <option>2</option>
                                  <option>3</option>
                                  <option>{% trans "Don't stick to stop" %}</option>
                                </select>
                              </div>
                            </form>`;
                        modalCb = () => {
                            let level = $('select[name="move-topic-up-level"]').val();
                            if (level === "{% trans "Don't stick to stop" %}") {
                                level = 10
                            } else {
                                level = parseInt(level)
                            }
                            patchTopic(
                                button.data('api-url'), {order: level}
                            )
                        };
                        break;
                    case 'open-topic':
                        modalTitle = "{% trans 'Open Topic' %}";
                        modalBody = "{% trans 'Please confirm your action' %}";
                        modalCb = () => {
                            patchTopic(button.data('api-url'), {closed: false});
                        };
                        break;
                    case 'close-topic':
                        modalTitle = "{% trans 'Close Topic' %}";
                        modalBody = "{% trans 'Please confirm your action' %}";
                        modalCb = () => {
                            patchTopic(button.data('api-url'), {closed: true});
                        };
                        break;
                    case 'hide-topic':
                        modalTitle = "{% trans 'Hide Topic' %}";
                        modalBody = "{% trans 'Please confirm your action' %}";
                        modalCb = () => {
                            patchTopic(button.data('api-url'), {hidden: true});
                        };
                        break;
                    case 'hide-reply':
                        modalTitle = "{% trans 'Hide Reply' %}";
                        modalBody = "{% trans 'Please confirm your action' %}";
                        modalCb = () => {
                            patchTopic(button.data('api-url'), {hidden: true});
                        };
                        break;
                    default:
                        modalTitle = modalBody = modalCb = '';
                }
                modal.find('.modal-confirm').click(modalCb);
                modal.find('.modal-title').text(modalTitle);
                modal.find('.modal-body').html(modalBody);
            })
        </script>
    {% endif %}
{% endblock %}