1/niji/niji/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from rest_framework import routers
from niji import api
from niji import views

api_router = routers.DefaultRouter()
api_router.register(r'topics', api.TopicApiView)
api_router.register(r'post', api.PostApiView)

app_name = 'niji'

urlpatterns = [
    url(r'^page/(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    url(r'^$', views.home, name='home'),
    url(r'index/', views.Index.as_view(), name='index'),
    url(r'^n/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', views.NodeView.as_view(), name='node'),
    url(r'^n/(?P<pk>\d+)/$', views.NodeView.as_view(), name='node'),
    url(r'^t/(?P<pk>\d+)/edit/$', views.edit_topic, name='edit_topic'),
    url(r'^t/(?P<pk>\d+)/append/$', views.create_appendix, name='create_appendix'),
    url(r'^t/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^t/(?P<pk>\d+)/$', views.TopicView.as_view(), name='topic'),
    url(r'^u/(?P<pk>\d+)/$', views.user_info, name='user_info'),
    url(r'^u/(?P<pk>\d+)/topics/page/(?P<page>[0-9]+)/$', views.UserTopics.as_view(), name='user_topics'),
    url(r'^u/(?P<pk>\d+)/topics/$', views.UserTopics.as_view(), name='user_topics'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^reg/$', views.reg_view, name='reg'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^search/$', views.search_redirect, name='search_redirect'),
    url(r'^search/(?P<keyword>.*?)/page/(?P<page>[0-9]+)/$', views.SearchView.as_view(), name='search'),
    url(r'^search/(?P<keyword>.*?)/$', views.SearchView.as_view(), name='search'),
    url(r'^t/create/$', views.create_topic, name='create_topic'),
    url(r'^notifications/$', views.NotificationView.as_view(), name='notifications'),
    url(r'^avatar/$', views.upload_avatar, name="upload_avatar"),
    url(r'^uploads/(?P<path>.*?)/(?P<subpath>.*?)/(?P<filename>.*?)/$', views.get_upload_file, name="get_upload_file"),
    url(r'^.*?/uploads/(?P<path>.*?)/(?P<subpath>.*?)/(?P<filename>.*?)/$', views.get_upload_file, name="get_upload_file"),
    url(r'^api/', include(api_router.urls)),
    url(r'^test$', views.test),
    url(r'^test/tang$', views.tang),
    url(r'^test/song$', views.song),
    url(r'^test/success$', views.success),
]

1/niji/urls.py
from django.urls import path
from django.conf.urls import include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('niji.urls')),
    path('tp/', include('tp.urls')),
    path('xj/', include('xj.urls')),
    path('NER/', include('NER.urls')),
    path('fhl/', include('fhl.urls'))
]

1/niji/niji/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django.conf import settings
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper
from .models import Topic, Appendix, ForumAvatar, Post
from django.utils.translation import ugettext as _

if 'pagedown' in settings.INSTALLED_APPS:
    use_pagedown = True
    from django import forms
    from pagedown.widgets import PagedownWidget
else:
    use_pagedown = False


class TopicForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TopicForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ['node', 'title', 'content_raw']
        labels = {
            'content_raw': _('Content'),
            'node': _('Node'),
            'title': _('Title'),
        }

    def save(self, commit=True):
        inst = super(TopicForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class TopicEditForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(TopicEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ('content_raw', )
        labels = {
            'content_raw': _('Content'),
        }


class AppendixForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.topic = kwargs.pop('topic', None)
        super(AppendixForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Appendix
        fields = ('content_raw', )
        labels = {
            'content_raw': _('Content'),
        }

    def save(self, commit=True):
        inst = super(AppendixForm, self).save(commit=False)
        inst.topic = self.topic
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ForumAvatarForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ForumAvatarForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = ForumAvatar
        fields = ('image', 'use_gravatar')
        labels = {
            'image': _('Avatar Image'),
            'use_gravatar': _("Always Use Gravatar")
        }

    def save(self, commit=True):
        inst = super(ForumAvatarForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ReplyForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(label='', widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic_id = kwargs.pop('topic_id', None)
        super(ReplyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Post
        fields = ('content_raw',)
        labels = {
            'content_raw': '',
        }

    def save(self, commit=True):
        inst = super(ReplyForm, self).save(commit=False)
        inst.user = self.user
        inst.topic_id = self.topic_id
        if commit:
            inst.save()
            self.save_m2m()
        return inst

1/niji/niji/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.conf import settings
from django.views.generic import ListView
from django.utils.translation import ugettext as _
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import Topic, Node, Post, Notification, ForumAvatar
from .forms import TopicForm, TopicEditForm, AppendixForm, ForumAvatarForm, ReplyForm
from .misc import get_query
import re
import os

EMAIL_REGEX = re.compile(r"[^@]+@[^@]+\.[^@]+")
User = get_user_model()


def get_default_ordering():
    return getattr(
        settings,
        "NIJI_DEFAULT_TOPIC_ORDERING",
        "-last_replied"
    )


def get_topic_ordering(request):
    query_order = request.GET.get("order", "")
    if query_order in ["-last_replied", "last_replied", "pub_date", "-pub_date"]:
        return query_order
    return get_default_ordering()


# Create your views here.
class Index(ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/test.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            *['order', get_topic_ordering(self.request)]
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['panel_title'] = _('New Topics')
        context['title'] = _('Index')
        context['show_order'] = True
        return context


class NodeView(ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/node.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().filter(
            node__id=self.kwargs.get('pk')
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            *['order', get_topic_ordering(self.request)]
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['node'] = node = Node.objects.get(pk=self.kwargs.get('pk'))
        context['title'] = context['panel_title'] = node.title
        context['show_order'] = True
        return context


class TopicView(ListView):
    model = Post
    paginate_by = 30
    template_name = 'niji/topic.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.visible().filter(
            topic_id=self.kwargs.get('pk')
        ).select_related(
            'user'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by('pub_date')

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        current = Topic.objects.visible().get(pk=self.kwargs.get('pk'))
        current.increase_view_count()
        context['topic'] = current
        context['title'] = context['topic'].title
        context['node'] = context['topic'].node
        context['form'] = ReplyForm()
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        current = Topic.objects.visible().get(pk=self.kwargs.get('pk'))
        if current.closed:
            return HttpResponseForbidden("Topic closed")
        topic_id = self.kwargs.get('pk')
        form = ReplyForm(
            request.POST,
            user=request.user,
            topic_id=topic_id
        )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('niji:topic', kwargs={'pk': topic_id})
            )


def user_info(request, pk):
    u = User.objects.get(pk=pk)
    return render(request, 'niji/user_info.html', {
        'title': u.username,
        'user': u,
        'topics': u.topics.visible().select_related('node')[:10],
        'replies': u.posts.visible().select_related('topic', 'user').order_by('-pub_date')[:30],
    })


class UserTopics(ListView):
    model = Post
    paginate_by = 30
    template_name = 'niji/user_topics.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.visible().filter(
            user_id=self.kwargs.get('pk')
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['user'] = User.objects.get(pk=self.kwargs.get('pk'))
        context['panel_title'] = context['title'] = context['user'].username
        return context


class SearchView(ListView):
    model = Topic
    paginate_by = 30
    template_name = 'niji/search.html'
    context_object_name = 'topics'

    def get_queryset(self):
        keywords = self.kwargs.get('keyword')
        query = get_query(keywords, ['title'])
        return Topic.objects.visible().filter(
            query
        ).select_related(
            'user', 'node'
        ).prefetch_related(
            'user__forum_avatar'
        ).order_by(
            get_topic_ordering(self.request)
        )

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['title'] = context['panel_title'] = _('Search: ') + self.kwargs.get('keyword')
        context['show_order'] = True
        return context


def search_redirect(request):
    if request.method == 'GET':
        keyword = request.GET.get('keyword')
        return HttpResponseRedirect(reverse('niji:search', kwargs={'keyword': keyword}))
    else:
        return HttpResponseForbidden('Post you cannot')


@login_required
def create_topic(request):
    if request.method == 'POST':
        form = TopicForm(request.POST, user=request.user)
        if form.is_valid():
            t = form.save()
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': t.pk}))
    else:
        form = TopicForm()

    return render(request, 'niji/create_topic.html', {'form': form, 'title': _('Create Topic')})


@login_required
def edit_topic(request, pk):
    topic = Topic.objects.get(pk=pk)
    if topic.reply_count > 0:
        return HttpResponseForbidden(_('Editing is not allowed when topic has been replied'))
    if not topic.user == request.user:
        return HttpResponseForbidden(_('You are not allowed to edit other\'s topic'))
    if request.method == 'POST':
        form = TopicEditForm(request.POST, instance=topic)
        if form.is_valid():
            t = form.save()
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': t.pk}))
    else:
        form = TopicEditForm(instance=topic)

    return render(request, 'niji/edit_topic.html', {'form': form, 'title': _('Edit Topic')})


@login_required
def create_appendix(request, pk):
    topic = Topic.objects.get(pk=pk)
    if not topic.user == request.user:
        return HttpResponseForbidden(_('You are not allowed to append other\'s topic'))
    if request.method == 'POST':
        form = AppendixForm(request.POST, topic=topic)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('niji:topic', kwargs={'pk': topic.pk}))
    else:
        form = AppendixForm()

    return render(request, 'niji/create_appendix.html', {
        'form': form, 'title': _('Create Appendix'), 'pk': pk
    })


@login_required
def upload_avatar(request):
    avatar = ForumAvatar.objects.filter(user_id=request.user.id).first()
    if request.method == 'POST':
        if avatar:
            form = ForumAvatarForm(request.POST, request.FILES, instance=avatar, user=request.user)
        else:
            form = ForumAvatarForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('niji:index'))
    else:
        if avatar:
            form = ForumAvatarForm(instance=request.user.forum_avatar)
        else:
            form = ForumAvatarForm()

    return render(request, 'niji/upload_avatar.html', {'form': form, 'title': _('Upload Avatar')})


def get_upload_file(request, path, subpath, filename):
    file_path = os.getcwd() + '/uploads/{}/{}/{}'.format(path, subpath, filename)
    if os.path.isfile(file_path):
        try:
            with open(file_path, 'rb') as f:
                image_data = f.read()
            return HttpResponse(image_data, content_type="image/png")
        except Exception as e:
            print(e)

    return HttpResponse(str('404: Not Found'))


@login_required
def notification_view(request):
    notifications = request.user.received_notifications.all().order_by('-pub_date')
    Notification.objects.filter(to=request.user).update(read=True)
    return render(request, 'niji/notifications.html', {
        'title': _("Notifications"),
        'notifications': notifications,
    })


class NotificationView(ListView):

    model = Notification
    paginate_by = 30
    template_name = 'niji/notifications.html'
    context_object_name = 'notifications'

    def get_queryset(self):
        Notification.objects.filter(to=self.request.user).update(read=True)
        return Notification.objects.filter(
            to=self.request.user
        ).select_related(
            'sender', 'topic', 'post'
        ).prefetch_related(
            'sender__forum_avatar', 'post__topic'
        ).order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)

1/niji/niji/templates/niji/widgets/authenticated_user_panel.html
{% load niji_tags %}
{% load i18n %}
<div class="panel panel-default">
    <!--<div class="panel-heading">NIJI APP</div>-->
    <div class="panel-body user-panel">
        <div class="panel-user-info">
            <div class="avatar-name">
                <a href="{% url "niji:upload_avatar" %}">
                    <img class="panel-avatar user-avatar" src="{% avatar_url request.user %}" alt=""/>
                </a>
                <span class="panel-username"><a href="{% url 'niji:user_info' request.user.pk %}">{{ request.user.username }}</a></span>
            </div>
            <div class="row panel-user-meta">
                <div class="col-xs-4 panel-user-meta-item">
                    <a href="{% url 'niji:user_topics' request.user.pk %}">
                        <div class="text-center">
                            <p class="panel-user-meta-item-value">
                                {{ request.user.topics.count }}
                            </p>
                            <p class="panel-user-meta-item-title">Topics</p>
                        </div>
                    </a>
                </div>
                <div class="col-xs-4 panel-user-meta-item">
                    <a href="{% url 'niji:user_info' request.user.pk %}">
                        <div class="text-center">
                            <p class="panel-user-meta-item-value">{{ request.user.posts.count }}</p>
                            <p class="panel-user-meta-item-title">Replies</p>
                        </div>
                    </a>
                </div>
                <div class="col-xs-4 panel-user-meta-item">
                    <a href="{% url 'niji:user_info' request.user.pk %}">
                        <div class="text-center">
                            <p class="panel-user-meta-item-value">{{ request.user.pk }}</p>
                            <p class="panel-user-meta-item-title">UID</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <ul class="list-group">
        <li class="list-group-item">
            <a href="{% url 'niji:create_topic' %}">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                {% trans 'Create Topic' %}
            </a>
        </li>
        <li class="list-group-item">
            <a class="text-success" href="{% url 'niji:notifications' %}">
                {% if unread_count %}
                    <span class="glyphicon glyphicon-gift" aria-hidden="true"></span>
                    {% blocktrans count unread_count=unread_count %}
                        {{ unread_count }} new notification
                        {% plural %}
                        {{ unread_count }} new notifications
                    {% endblocktrans %}
                {% else %}
                    <span class="text-muted">{% trans 'No new nofitications' %}</span>
                {% endif %}
            </a>
        </li>
        <li class="list-group-item">
            <a href="{% url 'niji:logout' %}">
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                {% trans "Log out" %}
            </a>
        </li>
    </ul>
</div>

1/niji/niji/templates/niji/widgets/node_info.html
{% load i18n %}
<div class="panel panel-default">
    <div class="panel-heading">{{ node.title }}</div>
    <div class="panel-body">
        <p>
            {{ node.description | safe }}
        </p>
    </div>
</div>

1/niji/niji/templates/niji/widgets/nodes.html
{% load i18n %}
<div class="panel panel-default">
    <div class="panel-heading">{% trans "Nodes" %}</div>
    <div class="panel-body">
        {% for node in nodes %}
            <a href="{% url 'niji:node' node.pk %}">
                <span class="label label-default meta-node">{{ node.title }}</span>
            </a>
        {% endfor %}
    </div>
</div>

1/niji/niji/templates/niji/widgets/pagedown.html
{% load i18n %}

<div class="wmd-wrapper" id="{{ id }}-wmd-wrapper">
    <div class="wmd-panel">
        <div id="{{ id|safe }}_wmd_button_bar"></div>
        <textarea{{ attrs|safe }}>{{ body }}</textarea>
    </div>
    {% if show_preview %}
        <p class="wmd-preview-title"><small>{% trans 'Preview' %}:</small></p>
        <div id="{{ id|safe }}_wmd_preview" class="wmd-panel wmd-preview"></div>
    {% endif %}
</div>

1/niji/niji/templates/niji/widgets/visitor_user_panel.html
{% load i18n %}
<div class="panel panel-default">
    <div class="panel-heading">NIJI APP</div>
    <div class="panel-body">
        NIJI is a forum app built with Django
        <hr/>
        <div class="row">
            <div class="col-md-6">
                <a href="{% url niji_login_url_name %}" class="btn btn-block btn-info">{% trans 'Log in' %}</a>
            </div>
            <div class="col-md-6">
                <a href="{% url niji_reg_url_name %}" class="btn btn-block btn-default">{% trans 'Reg' %}</a>
            </div>
        </div>
        <hr/>
{#        <p>#}
{#            <a href="#">Reset Password</a>#}
{#        </p>#}
    </div>
</div>